import { gzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { fetchPublic, validatePublicUrl } from '../floor-plans/fetch-public.js';
const response = (status, body = '', headers = {}) => ({ status, headers: new Headers(headers), body: [Buffer.from(body)] });
describe('fetchPublic', () => {
    it('fails closed for private URLs and redirects', async () => { await expect(validatePublicUrl('http://127.0.0.1/x')).rejects.toThrow(/public|private/); const calls=[]; const result = await fetchPublic('https://public.test/a', { respectRobots: false, lookup: async h => [{ address: '93.184.216.34' }], fetch: async (url) => { calls.push(url); return response(302, '', { location: 'http://127.0.0.1/private' }); } }); expect(result.blockedReason).toMatch(/public|private/); });
    it('honors robots disallow and 304 validators', async () => { const result = await fetchPublic('https://public.test/a', { lookup: async h => [{ address: '93.184.216.34' }], fetch: async url => url.endsWith('/robots.txt') ? response(200, 'User-agent: *\nDisallow: /a') : response(200) }); expect(result.blockedReason).toBe('robots-disallow'); const cached = await fetchPublic('https://cache.test/a', { lookup: async h => [{ address: '93.184.216.34' }], etag: 'x', fetch: async url => url.endsWith('/robots.txt') ? response(404) : response(304, '', { etag: 'x' }) }); expect(cached.notModified).toBe(true); });
    it('follows relative robots redirects and still obeys their rules', async () => { const calls=[]; const result=await fetchPublic('https://robots-redirect.test/a',{lookup:async()=>[{address:'93.184.216.34'}],fetch:async url=>{calls.push(url);return url.endsWith('/robots.txt')?response(302,'',{location:'/policy/first'}):url.endsWith('/first')?response(302,'',{location:'second'}):response(200,'User-agent: *\nDisallow: /a');}});expect(calls).toEqual(['https://robots-redirect.test/robots.txt','https://robots-redirect.test/policy/first','https://robots-redirect.test/policy/second']);expect(result.blockedReason).toBe('robots-disallow'); });
    it('decodes compressed public sitemaps before parsing', async()=>{const body=Buffer.from('<urlset><url><loc>https://compressed.test/a</loc></url></urlset>');const result=await fetchPublic('https://compressed.test/sitemap.xml.gz',{respectRobots:false,lookup:async()=>[{address:'93.184.216.34'}],fetch:async()=>response(200,gzipSync(body),{'content-type':'application/gzip'})});expect(result.body.equals(body)).toBe(true);expect(result.headers.contentType).toBe('application/xml');});
    it('aborts oversized bodies', async () => { await expect(fetchPublic('https://public.test/a', { respectRobots: false, maxBytes: 2, lookup: async h => [{ address: '93.184.216.34' }], fetch: async () => response(200, 'abcd') })).rejects.toThrow(/maxBytes/); });
});
