services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    # Mount local frontend code for live reload
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      API_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    # Mount local backend code for live reload
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Use nodemon for live reload in development
    command: npx nodemon index.js

  db:
    image: my-postgis:16-3.5-arm64
    restart: always
    environment:
      POSTGRES_DB: consensus
      POSTGRES_USER: consensus
      POSTGRES_PASSWORD: consensus
    ports:
      - "5432:5432"
    volumes:
      - pgdata_arm_postgis:/var/lib/postgresql/data

    command: >
      postgres
      -c max_wal_size=8GB
      -c min_wal_size=2GB
      -c checkpoint_completion_target=0.9
      -c wal_compression=on

volumes:
  pgdata_arm_postgis:
    external: true
    name: pgdata_arm_postgis
