#!/usr/bin/env python3
"""Generate browser CARTO configuration from a local .env, without committing the key."""

import argparse
import json
import os
from pathlib import Path
import re


def build_config(key):
    if not key or not re.fullmatch(r"[A-Za-z0-9_-]+", key):
        raise ValueError("Set a valid CARTO_BASEMAP_API_KEY in the .env file")
    return """// Generated by scripts/build-carto-config.py; do not commit this file.
globalThis.__cartoBasemaps = Object.freeze({
  tileUrl(template) {
    return template + (template.includes('?') ? '&' : '?') + 'key=' + %s;
  }
});
""" % json.dumps(key)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--env", required=True, type=Path, help="Local .env containing the key")
    parser.add_argument("--out", required=True, type=Path, help="Ignored carto-config.js to generate")
    args = parser.parse_args()
    key = os.environ.get("CARTO_BASEMAP_API_KEY", "")
    if not key and args.env.exists():
        match = re.search(r"^\s*(?:export\s+)?CARTO_BASEMAP_API_KEY\s*=\s*(.*?)\s*$", args.env.read_text(), re.M)
        if match:
            key = match[1].split(" #", 1)[0].strip().strip("\"'")
    try:
        content = build_config(key)
    except ValueError as error:
        parser.error(str(error))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content)
    print("CARTO browser configuration generated (key omitted).")


if __name__ == "__main__":
    main()
